ENH - Add logo and favicon to docs
jax-ml/jax-ai-stack pull request #114
Opened 2024-11-26 13:28 UTC by trallard

> !NOTE
> I started this PR off the branch in #65, so that PR must be merged before this one

This PR:

- Moves the logo and favicon one level up in the `_static` directory so that this can be rendered by Sphinx book
- Updates the paths to the favicon and logo on the landing page
- Changes the URL to the tutorial to relative URLs (was pointing to the built RTD docs)

2024-11-26 14:24 UTC, pavithraes approved these changes
Thanks, Tania. Looks good to me. :)

2024-12-02 18:39 UTC, jakevdp commented
What's the purpose of moving all the files here? This is going to cause conflicts with every other in-flight PR, so I'd lean toward not merging this change.

Can we add the logo and favicon without modifying the file structure of the repo?

2024-12-02 19:04 UTC, jakevdp commented
Ah, got it. In that case we need to wait for #65 to be merged, at which point we can rebase this and the diff should be small.

2024-12-03 20:48 UTC, jakevdp commented
OK, the style update is merged. Can you rebase this? Thanks!

2024-12-03 22:00 UTC, jakevdp requested changes

2024-12-03 22:03 UTC, jakevdp commented on docs/source/_static/ai-stack-logo.svg
Also, I don't understand the need to move this out of the `images` subdirectory. Can you elaborate on the reason?

2024-12-03 22:11 UTC, jakevdp approved these changes
Thanks!

2024-12-03 22:26 UTC, merged