Added JAX domain example, vision image segmentation
jax-ml/jax-ai-stack pull request #93
Opened 2024-11-12 18:25 UTC by vfdev-5

2024-11-12 18:26 UTC, vfdev-5 commented
@melissawm can you please review

2024-11-12 21:03 UTC, jakevdp commented on docs/JAX_examples_image_segmentation.md
> +## Image segmentation with JAX
This should be an H1 header

2024-11-12 21:25 UTC, jakevdp commented
One last build issue:
```
/home/docs/checkouts/readthedocs.org/user_builds/jax-ai-stack/checkouts/93/docs/JAX_examples_image_segmentation.ipynb:290006: WARNING: image file not readable: attachment:ed48cb36-b8c8-442f-b626-28e403b61ca2.png [image.not_readable]
```

2024-11-12 21:25 UTC, vfdev-5 commented
There is a warning in the readthedocs:
```
/home/docs/checkouts/readthedocs.org/user_builds/jax-ai-stack/checkouts/93/docs/JAX_examples_image_segmentation.ipynb:290006: WARNING: image file not readable: attachment:ed48cb36-b8c8-442f-b626-28e403b61ca2.png [image.not_readable]
looking for now-outdated files... none found
```
complaining about this text : 
```
"![image.png](attachment:ed48cb36-b8c8-442f-b626-28e403b61ca2.png)\n",
```
Image is attached in the jupyter notebook:
```
   "attachments": {
    "ed48cb36-b8c8-442f-b626-28e403b61ca2.png": {
     "image/png": <data>
    }
```
but this seems like not supported in readthedocs...
Should we create `assets` folder in the docs?

2024-11-12 21:26 UTC, jakevdp commented on docs/JAX_examples_image_segmentation.md
> +![image.png](attachment:ed48cb36-b8c8-442f-b626-28e403b61ca2.png)
Did you mean to include this image in the PR?

2024-11-12 22:17 UTC, jakevdp commented on docs/JAX_examples_image_segmentation.md
> +![image.png](attachment:ed48cb36-b8c8-442f-b626-28e403b61ca2.png)
It looks like notebook attachments are not supported: https://github.com/executablebooks/MyST-NB/issues/230

Maybe we can put it separately in an `html_static_path`

2024-11-13 17:04 UTC, melissawm requested changes
Left some textual suggestions but mainly I can't get the notebook to run completely, potentially because of recent changes to flax/nnx.

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Let us implement confusion matrix metric derived from [`nnx.Metric`](https://flax.readthedocs.io/en/latest/api_reference/flax.nnx/training/metrics.html#flax.nnx.metrics.Metric). Confusion matrix will
```suggestion
Now, we will implement a confusion matrix metric derived from [`nnx.Metric`](https://flax.readthedocs.io/en/latest/api_reference/flax.nnx/training/metrics.html#flax.nnx.metrics.Metric). A confusion matrix will help us to compute the Intersection-Over-Union (IoU) metric per class and on average. Finally, we can also compute the accuracy metric using the confusion matrix.
```

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Let us now define training and evaluation steps
```suggestion
Next, let's define training and evaluation steps:
```

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Metrics like IoU per class, mean IoU and accuracy will be computed using the confusion matrix in the evaluation code.
```suggestion
We will also define metrics we want to compute during the evaluation phase: total loss and confusion matrix computed on training and validation datasets. Finally, we define helper objects to store the metrics history.
Metrics like IoU per class, mean IoU and accuracy will be computed using the confusion matrix in the evaluation code.
```

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Let us check saved models
```suggestion
We can check the saved models:
```

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Let us visualize collected metrics
```suggestion
and visualize collected metrics:
```

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Let us visualize model predictions on validation data
```suggestion
Next, we will visualize model predictions on validation data:
```

2024-11-13 17:04 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +We can see that model can roughly predict the shape of the animal and the background and struggles with predicting the boundary. We can also observe that model starts overfitting according to the tra
```suggestion
We can see that model can roughly predict the shape of the animal and the background and struggles with predicting the boundary. We can also observe that the model starts overfitting according to the training and validation loss curves on the above plot. Carefully choosing hyperparameters and another optimizer like Adam we may achieve better results.
```

2024-11-13 20:03 UTC, vfdev-5 commented on docs/JAX_examples_image_segmentation.md
> +Let's install required python packages
It is described just above: 
> In the code below we make a choice of using OpenCV and Pillow to read images and masks as NumPy arrays, [Albumentations](https://github.com/albumentations-team/albumentations) for data augmentations and
[`grain`](https://github.com/google/grain/) for batched data loading. This choice of tools is not restricted and can be changed to any other alternative ones, e.g. [tensorflow_dataset](https://www.tensorflow.org/datasets) or [torchvision](https://pytorch.org/vision/stable/index.html).

2024-11-13 20:43 UTC, vfdev-5 commented on docs/JAX_examples_image_segmentation.md
> +class InstanceNorm(nnx.GroupNorm):
Yes, there is a typo in `PatchEmbeddingBlock`, thansk for catching it

2024-11-13 21:12 UTC, vfdev-5 commented on docs/JAX_examples_image_segmentation.md
> +For semantic segmentation task we can define the loss function as a sum of Cross-Entropy loss and Jaccard losses.
I can add the following:
> The Cross-Entropy loss function is a standard loss function for a multi-class classification tasks and the Jaccard loss function helps directly optimizing Intersection-over-Union measure for semantic segmentation.

I do not have a good reference on Jaccard Loss function except this one : https://arxiv.org/pdf/1705.08790 where they proposed Lovasz-Softmax loss as another surrogate loss function to optimize IoU measure.

2024-11-13 21:17 UTC, melissawm commented on docs/JAX_examples_image_segmentation.md
> +Let's install required python packages
OOps sorry I missed that! Feel free to ignore then :)

2024-11-14 21:18 UTC, jakevdp commented
I'm not sure how to address that.

2024-11-18 21:14 UTC, jakevdp reviewed
Looks good overall – in the notebook, there are a lot of warnings about corrupt JPEG data. Should we worry about these? Is there any way to silence them?

2024-11-18 21:14 UTC, jakevdp commented on docs/JAX_examples_image_segmentation.md
> +# Image segmentation with JAX
Let's change this to something more specific, like "UNETR for image segmentation"

2024-11-18 21:14 UTC, jakevdp commented on docs/JAX_examples_image_segmentation.md
> +```
Remove empty cell

2024-11-18 21:45 UTC, jakevdp commented
> > there are a lot of warnings about corrupt JPEG data
> 
> There few corrupted images and warning is raised by OpenCV when reading them, in this case the fallback is using Pillow to read them. Using only Pillow for reading images is a bit slow. I can try to slience the warnings

Sounds good. Alternatively you could call these out and mention why they're non-problematic in this case.

2024-11-19 16:25 UTC, vfdev-5 commented
@jakevdp I applied the suggestions and removed indices of the data which raised warnings. Please review again. Thanks!

2024-11-19 21:33 UTC, jakevdp approved these changes

2024-11-19 21:40 UTC, merged