Update JAX AI Stack VAE tutorial
jax-ml/jax-ai-stack pull request #96
Opened 2024-11-15 17:50 UTC by 8bitmp3

@jakevdp

2024-11-15 22:35 UTC, jakevdp requested changes
Thanks for this! I love the new links and cross-references; I think it adds a lot without making the text too overwhelming.

One small typo below; also let's switch back to first-person phrasing please.

2024-11-15 22:35 UTC, jakevdp commented on docs/digits_vae.md
> +Next, you need to d efine the loss function. The are two components to the model that you want to ensure:
stray space in "define"

2024-11-20 22:04 UTC, 8bitmp3 commented
@jakevdp

2024-11-20 22:13 UTC, jakevdp approved these changes
Thanks!

2024-11-20 22:14 UTC, merged